---
el:
  hosts:
    centos8:
      ansible_connection: docker
deb:
  hosts:
    ubuntu:
      ansible_connection: docker
      ansible_python_interpreter: /usr/bin/python3
local:
  hosts:
    localhost:
      ansible_connection: local
